//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseGradeB.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseGradeB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAddCourse {
            get {
                object obj = ResourceManager.GetObject("btnAddCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnDeleteCourse {
            get {
                object obj = ResourceManager.GetObject("btnDeleteCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap calc_save_64 {
            get {
                object obj = ResourceManager.GetObject("calc_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;DomainList&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;語文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;數學&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;社會&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;自然與生活科技&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;健康與體育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;藝術與人文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;General&quot;&gt;綜合活動&lt;/Domain&gt;
        ///	&lt;!-- &lt;Domain Type=&quot;Special&quot;&gt;實用語文&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;實用數學&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;社會適應&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;生活教育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;休閒教育&lt;/Domain&gt;
        ///	&lt;Domain Type=&quot;Special&quot;&gt;職業 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DefaultDomainList {
            get {
                return ResourceManager.GetString("DefaultDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Ordinal&gt;
        ///	&lt;Subjects&gt;
        ///		&lt;Subject Name=&quot;國語文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;國文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;英文&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;英語&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;數學&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;歷史&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;地理&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;公民&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;理化&quot; EnglishName=&quot;&quot;/&gt;
        ///		&lt;Subject Name=&quot;生物&quot; EnglishName=&quot;&quot;/&gt;
        ///	&lt;/Subjects&gt;
        ///	&lt;Domains&gt;
        ///		&lt;Domain Name=&quot;語文&quot; EnglishName=&quot;&quot; Group=&quot;&quot;/&gt;
        ///		&lt;Domain Name=&quot;數學&quot; Engl [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DefaultSubjectOrdinal {
            get {
                return ResourceManager.GetString("DefaultSubjectOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap exam_write_64 {
            get {
                object obj = ResourceManager.GetObject("exam_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loadering {
            get {
                object obj = ResourceManager.GetObject("loadering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap network_lock_64 {
            get {
                object obj = ResourceManager.GetObject("network_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap notepad_lock_64 {
            get {
                object obj = ResourceManager.GetObject("notepad_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap organigram_refresh_64 {
            get {
                object obj = ResourceManager.GetObject("organigram_refresh_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap teacher_64 {
            get {
                object obj = ResourceManager.GetObject("teacher_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
